.TH ajaxterm "1" "Jul 2006" "ajaxterm 0.7" "User commands"
.SH NAME
ajaxterm \- Web based terminal written in python

.SH DESCRITPION
\fBajaxterm\fR is a web based terminal written in python and some AJAX
javascript for client side.
It can use almost any web browser and even works through firewalls.

.SH USAGE
\fBajaxterm\fR [options]

.SH OPTIONS
A summary of the options supported by \fBajaxterm\fR is included below.
.TP
\fB\-h\fR, \fB\-\-help\fR
show the help message and exit
.TP
\fB\-p\fR PORT, \fB\-\-port\fR=\fIPORT\fR
Set the TCP port (default: 8022)
.TP
\fB\-c\fR CMD, \fB\-\-command\fR=\fICMD\fR
set the command (default: /bin/login or ssh localhost)
.TP
\fB\-l\fR, \fB\-\-log\fR
log requests to stderr (default: quiet mode)
.TP
\fB\-d\fR, \fB\-\-daemon\fR
run as daemon in the background
.TP
\fB\-P\fR PIDFILE, \fB\-\-pidfile\fR=\fIPIDFILE\fR
set the pidfile (default: /var/run/ajaxterm.pid)
.TP
\fB\-i\fR INDEX_FILE, \fB\-\-index\fR=\fIINDEX_FILE\fR
default index file (default: ajaxterm.html)
.TP
\fB\-u\fR UID, \fB\-\-uid\fR=\fIUID\fR
Set the daemon's user id
.TP
\fB\-s\fR SERVERPORT, \fB\-\-serverport\fR=\fISERVERPORT\fR
Use a different port than 22 to connect to the ssh
server
.TP
\fB\-t\fR TOKEN, \fB\-\-token\fR=\fITOKEN\fR
Set authorization token. If this option is passed on the command line, the
given token must be used when accessing ajaxterm (by adding a ?token=something
request argument).
.TP
\fB\-T\fR SECONDS, \fB\-\-terminate-on-idle\fR=\fISECONDS\fR
Terminate if idle for more than SEC seconds (0 means never)

.SH AUTHOR
Antony Lesuisse <al@udev.org>

Adopted to UTF-8 by Sergej Pupykin <ps@lx-ltd.ru>

This manual page was written for the Debian system by
Julien Valroff <julien@debian.org> (but may be used by others).

.SH "REPORTING BUGS"
Report any bugs to the author: Antony Lesuisse <al@udev.org>

.SH COPYRIGHT
Copyright Antony Lesuisse <al@udev.org>

.SH SEE ALSO
- \fBajaxterm\fR wiki page: http://antony.lesuisse.org/qweb/trac/wiki/AjaxTerm
.br
- \fBajaxterm\fR forum: http://antony.lesuisse.org/qweb/forum/viewforum.php?id=2
